version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    networks:
      - "information_network"
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9094:9092"
    environment:
      KAFKA_CREATE_TOPICS: "LENZDRGB610:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - "information_network"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    links:
      - "zookeeper"

#  nifi:
#    image: apache/nifi:latest
#    ports:
#      - 8080 # Unsecured HTTP Web Port
#    environment:
#      - NIFI_WEB_HTTP_PORT=8080
#      - NIFI_CLUSTER_IS_NODE=true
#      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
#      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
#      - NIFI_ELECTION_MAX_WAIT=1 min

 
networks:
  information_network:
