version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    container_name: zookeeper0
 
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    hostname: kafka
    container_name: kafka
    ports:
      - "9094:9092"
    #expose: 
    #  - "29092"
    environment:
      KAFKA_CREATE_TOPICS: "NiFi:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - information-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
#  nifi:
#    image: apache/nifi:latest
#    ports:
#      - 8080 # Unsecured HTTP Web Port
#    environment:
#      - NIFI_WEB_HTTP_PORT=8080
#      - NIFI_CLUSTER_IS_NODE=true
#      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
#      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
#      - NIFI_ELECTION_MAX_WAIT=1 min

#  producer:
#    build: 
#      context: ./go
#      dockerfile: Dockerfile
#    image: kafka-producer 
#    restart: on-failure   
#    depends_on:
#      kafka:
#         condition: service_healthy

networks:
  information-network:
  operation-network:
  service-network:
