version: '3'
services:
# ZOOKEEPER
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    networks:
      - "information_network"
      
# HiveMQ
  hivemq:
    image: hivemq/hivemq-ce
    hostname: hivemq
    ports: 
      - "1883:1883"
      - "8080:8080"
      - "8000:8000"
    networks:
      - "information_network"

# mqtt2kafka
  mqtt2kafka:
    image: marmaechler/mqtt2kafkabridge:latest
    hostname: mqtt2kafka
    depends_on:
      - kafka1
      - hivemq
    restart: always
    environment:
      KAFKA_BROKER_HOST: kafka1:19091
      MQTT_BROKER_HOST: hivemq:1883
    volumes:
      - ./mqtt2kafkabridge/logs:/opt/mqtt2kafkabridge/logs
    networks:
      - "information_network"

# KAFKA 1
  kafka1:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_CREATE_TOPICS: "LENZDRGB610:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka1:19091,OUTSIDE://localhost:9091
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:19091,OUTSIDE://localhost:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - "information_network"
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - "zookeeper"
    links:
      - "zookeeper"
# KAFKA 2
  kafka2:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    hostname: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "LENZDRGB611:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka2:19092,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:19092,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - "information_network"
    volumes:
      - ./data/kafka2/data:/var/lib/kafka/data
    depends_on:
      - "zookeeper"
    links:
      - "zookeeper"
# KAFKA 3
  kafka3:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    hostname: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_CREATE_TOPICS: "LENZDRGB612:1:1" # topic:partition:replicas
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka3:19093,OUTSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:19093,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - "information_network"
    volumes:
      - ./data/kafka3/data:/var/lib/kafka/data
    depends_on:
      - "zookeeper"
    links:
      - "zookeeper"
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
    networks:
      - "information_network"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
 
networks:
  information_network:
