# This is a basic workflow to help you get started with Actions

name: Branch experimental

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [  experimental ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: preparation
        run: docker-compose down && docker container prune --force  && docker system prune -a
        
      - name: setup environment
        run: docker-compose up --d
        
        # Runs a single command using the runners shell
      - name: cleanup
        run: docker-compose down && docker container prune --force && docker system prune -a
    

        
        
